const seed = [{
    name: "T-Shirt",
    brand: "Zara",
    description: "White crew neck",
    category: "Fashion",
    image: "x",
    price: 20,
},
{
    name: "Macbook pro",
    brand: "Apple",
    description: "Macbook pro 13 inch",
    category: "Electronics",
    image: "x",
    price: 2000,
},
{
    name: "Air-fryer",
    brand: "Phillips",
    description: "5 litre, black",
    category: "Household",
    image: "x",
    price: 700,
},
{
    name: "Ice-cream",
    brand: "Haägen Daź",
    description: "Chocolate",
    category: "Food & Beverages",
    image: "x",
    price: 13,
},
{
    name: "Vitamin-C",
    brand: "Swisse",
    description: "100 capsule",
    category: "Health & Wellness",
    image: "x",
    price: 70,
},
{
    name: "Facial Cleanser",
    brand: "Innis free",
    description: "Whitening, 100ml",
    category: "Beauty & personal care",
    image: "x",
    price: 28,
}]
module.exports = seed;