const productsSeed = [
    {
        name: "T-Shirt",
        brand: "Zara",
        description: "Grey crew neck",
        category: "Fashion",
        image: "https://i.ibb.co/5MnkdgT/grey-t-shirt-01.jpg",
        price: 20,
    },
    {
        name: "Macbook Pro",
        brand: "Apple",
        description: "Macbook pro 13 inch",
        category: "Electronics",
        image: "https://i.ibb.co/Swcgm6g/Macbook-01.jpg",
        price: 2000,
    },
    {
        name: "Air-fryer",
        brand: "Philips",
        description: "Black 5 litre",
        category: "Household",
        image: "https://i.ibb.co/61KL9gc/airfryer-01.jpg",
        price: 500,
    },
    {
        name: "Ice-cream",
        brand: "Häagen Dazs",
        description: "Belgium Chocolate",
        category: "Food & Beverages",
        image: "https://i.ibb.co/g9f9qHV/ice-cream-01.jpg",
        price: 13,
    },
    {
        name: "Vitamin-C",
        brand: "Swisse",
        description: "300 capsule",
        category: "Health & Wellness",
        image: "https://i.ibb.co/BVZj9Hk/vitamin-c-01.jpg",
        price: 120,
    },
    {
        name: "Facial Cleanser",
        brand: "Innisfree",
        description: "Whitening, 100ml",
        category: "Beauty & Personal Care",
        image: "https://i.ibb.co/QX1ryV8/facial-cleanser-01.jpg",
        price: 18,
    },
    {
        name: "Eyebrow pencil",
        brand: "Benefit",
        description: "Brow pencil and brush",
        category: "Beauty & Personal Care",
        image: "https://i.ibb.co/rFKbqDW/eyebrow-pencil-01.jpg",
        price: 39,
    },
    {
        name: "Face Lifting Cream",
        brand: "Olay",
        description: "Micro-sculpting cream,48g",
        category: "Beauty & Personal Care",
        image: "https://i.ibb.co/PFbHLSF/olay-01.jpg",
        price: 48,
    },
    {
        name: "Foundation Powder",
        brand: "Chanel",
        description: "Bronze tone shade,20ml",
        category: "Beauty & Personal Care",
        image: "https://i.ibb.co/V9XBwjM/chanel-01.jpg",
        price: 200,
    }, {
        name: "Lip Gloss",
        brand: "Jeffree Star",
        description: "4 colours- blue, purple, peach, coral, waterproof",
        category: "Beauty & Personal Care",
        image: "https://i.ibb.co/LYD1x0b/Lip-gloss-01.jpg",
        price: 34,
    }, {
        name: "Collagen Supplement",
        brand: "SR",
        description: "Collagen pills, 50 capsules",
        category: "Health & Wellness",
        image: "https://i.ibb.co/ZJPfBTX/collagen.jpg",
        price: 69,
    }, {
        name: "Diet Pills",
        brand: "Innosupps",
        description: "Night slimming pills60 capsules",
        category: "Health & Wellness",
        image: "https://i.ibb.co/yQRC9PJ/slimming-pill-01.jpg",
        price: 53,
    }, {
        name: "Chicken Essence",
        brand: "Brand's",
        description: "12 bottles original essence of chicken, 42g",
        category: "Health & Wellness",
        image: "https://i.ibb.co/TWwpH47/Chicken-essence-01.jpg",
        price: 48,
    }, {
        name: "Protein Powder",
        brand: "GNC",
        description: "100% gold standard whey protein powder, 2.9kg",
        category: "Health & Wellness",
        image: "https://i.ibb.co/sw0XZZF/protein-01.jpg",
        price: 79,
    }, {
        name: "Potato Chips",
        brand: "Kettle",
        description: "Maple bacon flavour, 241g",
        category: "Food & Beverages",
        image: "https://i.ibb.co/99T639N/potato-chip-01.jpg",
        price: 6.95,
    }, {
        name: "Beer",
        brand: "Heineken",
        description: "330ml",
        category: "Food & Beverages",
        image: "https://i.ibb.co/gDCW2fR/beer-01.jpg",
        price: 5.95,
    }, {
        name: "Yogurt",
        brand: "Dairy Farmers",
        description: "Vanilla flavour, 150g",
        category: "Food & Beverages",
        image: "https://i.ibb.co/xMBqfbn/yogurt-01.jpg",
        price: 2.90,
    }, {
        name: "Fresh Milk",
        brand: "Magnolia",
        description: "Low fat fresh milk, 500ml",
        category: "Food & Beverages",
        image: "https://i.ibb.co/XFRKHtS/fresh-milk-01.jpg",
        price: 3.25,
    }, {
        name: "Fry Pan",
        brand: "Wmf",
        description: "30 cm stainless steel, non stick pan",
        category: "Household",
        image: "https://i.ibb.co/wsQCnNK/fry-pan-01.jpg",
        price: 39,
    }, {
        name: "Mini Refrigerator",
        brand: "Galanz",
        description: "Mini black retro refrigerator",
        category: "Household",
        image: "https://i.ibb.co/Sv7Tfzf/fridge-01.jpg",
        price: 690,
    }, {
        name: "Vacuum Cleaner",
        brand: "Dyson",
        description: "Cord-free vacuum cleaner",
        category: "Household",
        image: "https://i.ibb.co/71RW1kg/dyson-01.jpg",
        price: 599,
    }, {
        name: "Air Purifier",
        brand: "Philips",
        description: "White air purifier",
        category: "Household",
        image: "https://i.ibb.co/kJt7dSb/Air-purifier-01.jpg",
        price: 499,
    }, {
        name: "GoPro Camera",
        brand: "GoPro",
        description: "Black waterproof action camera with 2.0 stabilization",
        category: "Electronics",
        image: "https://i.ibb.co/NFDHTMV/go-pro-01.jpg",
        price: 299,
    }, {
        name: "Wireless Earbuds",
        brand: "Skullcandy",
        description: "Light-blue, noise cancelling",
        category: "Electronics",
        image: "https://i.ibb.co/bsy7f82/ear-buds-01.jpg",
        price: 48,
    }, {
        name: "Powerbank",
        brand: "Duracell",
        description: "Portable charge 20,000 mAh",
        category: "Electronics",
        image: "https://i.ibb.co/WgvtvTG/powerbank-01.jpg",
        price: 18,
    }, {
        name: "Xiaomi Handphone",
        brand: "Xiaomi",
        description: "Xiaomi Mi 10T pro",
        category: "Electronics",
        image: "https://i.ibb.co/gr17Mgw/xiaomi-01.jpg",
        price: 18,
    }, {
        name: "Men's Briefcase",
        brand: "The Bridge",
        description: "Black faux leather, 30cm x 25cm briefcase",
        category: "Fashion",
        image: "https://i.ibb.co/w4bPyXX/briefcase-01.jpg",
        price: 18,
    }, {
        name: "Men's Long Sleeves Shirt",
        brand: "Casa Di Moda",
        description: "Sky blue long sleeves button-up shirt",
        category: "Fashion",
        image: "xhttps://i.ibb.co/gMS1RtC/shirt-01.jpg",
        price: 49,
    }, {
        name: "Women's Classic Heels",
        brand: "Zara",
        description: "Black, 5 inch stilettos",
        category: "Fashion",
        image: "https://i.ibb.co/sjhVPLP/heels-01.jpg",
        price: 55,
    }, {
        name: "Women's Sling Bag",
        brand: "Gideban",
        description: "Grey faux leather sling bag",
        category: "Fashion",
        image: "https://i.ibb.co/7GL82RL/handbag-01.jpg",
        price: 52,
    }, {
        name: "Mini Fish Tank & Flower Pot",
        brand: "Fish Town",
        description: "Amphibian Eco-aquarium fish tank and flower pot",
        category: "Pets",
        image: "https://i.ibb.co/6N1LZWQ/fish-tank-01.jpg",
        price: 25,
    }, {
        name: "Cat Scratcher",
        brand: "PetFusion",
        description: "Cat scratcher lounge",
        category: "Pets",
        image: "https://i.ibb.co/2StbDj5/cat-scratch-01.jpg",
        price: 49,
    }, {
        name: "Dog Squeaker Toy",
        brand: "Pearhead",
        description: "Sushi plush squeaker dog toys",
        category: "Pets",
        image: "https://i.ibb.co/ch2FvKN/squeaker-toy-for-dog-01.jpg",
        price: 18,
    }, {
        name: "Dog Carrier",
        brand: "Mutts & Hounds",
        description: "Grey shoulder carrier, 30cm x 25cm",
        category: "Pets",
        image: "https://i.ibb.co/GRBZDWK/dog-carrier-01.jpg",
        price: 98,
    }, {
        name: "Dog Kibbles",
        brand: "Holistic",
        description: "5kg lamb & salmon air dried kibbles",
        category: "Pets",
        image: "https://i.ibb.co/C0Xsq60/kibbles-01.jpg",
        price: 18,
    }, {
        name: "Lululemon Yoga at",
        brand: "Lululemon",
        description: "3 colours- black, grey, pink",
        category: "Sports & Lifestyle",
        image: "https://i.ibb.co/47tCy94/yoga-mat-01.jpg",
        price: 100,
    }, {
        name: "Dumbbell Weight Lifting Equipment",
        brand: "Azj Trading",
        description: "4 sets of weight 10kg -30kg, black cast iron",
        category: "Sports & Lifestyle",
        image: "https://i.ibb.co/D7pgmTT/weighs-01.jpg",
        price: 90,
    }, {
        name: "Under Armour Backpack",
        brand: "Under Armour",
        description: "Grey backpack",
        category: "Sports & Lifestyle",
        image: "https://i.ibb.co/CnQR53B/under-armour-01.jpg",
        price: 70,
    }, {
        name: "Nike Air Women's Top",
        brand: "Nike",
        description: "Pink women's short sleeve crop top",
        category: "Sports & Lifestyle",
        image: "https://i.ibb.co/tmrL9Hs/nike-01.jpg",
        price: 33,
    }, {
        name: "Superstar Sneakers",
        brand: "Adidas",
        description: "Adidas Superstar sneakers",
        category: "Sports & Lifestyle",
        image: "https://i.ibb.co/wRGWT0S/adidas-shoes-01.jpg",
        price: 90,
    }, {
        name: "Baby Crib Bed",
        brand: "Plhmia baby",
        description: "50cm width x 100cm lenght x 120cm height",
        category: "Babies & Toys",
        image: "https://i.ibb.co/WgvtvTG/powerbank-01.jpg",
        price: 210,
    }, {
        name: "Baby Diapers",
        brand: "Huggies",
        description: "Size xs - xl",
        category: "Babies & Toys",
        image: "https://i.ibb.co/xg6871D/diaper-01.jpg",
        price: 25,
    }, {
        name: "Baby Jumpers",
        brand: "Flora babies",
        description: "Navy, 2 months - 1 year old size available",
        category: "Babies & Toys",
        image: "https://i.ibb.co/vYCcyMp/baby-clothes-01.jpg",
        price: 20,
    }, {
        name: "Baby Shoes",
        brand: "Baby bubble",
        description: "Blue shoes for age 5 months - 3 years old size available",
        category: "Babies & Toys",
        image: "https://i.ibb.co/GcpbL6j/baby-shoes-01.jpg",
        price: 15,
    }, {
        name: "Baby Soft Toy",
        brand: "Frog's",
        description: "Multi-colour soft toy for age 1 months - 1 years old",
        category: "Babies & Toys",
        image: "https://i.ibb.co/b3GNzzg/soft-toy-01.jpg",
        price: 22,
    }, {
        name: "Beads",
        brand: "Grimm's",
        description: "30 wooden beads, multi-colours",
        category: "Hobbies & Craft",
        image: "https://i.ibb.co/frG4cvm/beads-01.jpg",
        price: 12,
    }, {
        name: "Cutting Mat",
        brand: "Dafa",
        description: "Cutting mat and craft knife",
        category: "Hobbies & Craft",
        image: "https://i.ibb.co/5WQPnHp/craft-knife-cutting-mat-01.jpg",
        price: 7,
    }, {
        name: "Crochet Hooks",
        brand: "Knit Wit",
        description: "15 size Aluminum Crochet Hooks",
        category: "Hobbies & Craft",
        image: "https://i.ibb.co/Mk1J1XQ/knit-hook-01.jpg",
        price: 2,
    }, {
        name: "Origami Paper",
        brand: "Paper craft",
        description: "50 pieces colour origami paper",
        category: "Hobbies & Craft",
        image: "https://i.ibb.co/vjb1Ncd/craft-paper-01.jpg",
        price: 9,
    }, {
        name: "Pottery Tools",
        brand: "Zart Art",
        description: "Pottery 8 pieces tool set",
        category: "Hobbies & Craft",
        image: "https://i.ibb.co/j4rrYfy/pottery-01.jpg",
        price: 25,
    }, {
        name: "Fountain Pen",
        brand: "Line D",
        description: "Black, Gold Fountain Pen",
        category: "Books & Stationeries",
        image: "https://i.ibb.co/mhG3ntz/pen-01.jpg",
        price: 18,
    }, {
        name: "The Skinny Steamer Recipe Book",
        brand: "Cook Nation",
        description: "Steam food recipe book",
        category: "Books & Stationeries",
        image: "https://i.ibb.co/QrPy38d/recipie-book-01.jpg",
        price: 22,
    }, {
        name: "Harry Potter Fiction Book",
        brand: "Levine Books",
        description: "Full set of Harry Potter collection",
        category: "Books & Stationeries",
        image: "https://i.ibb.co/L6PWbX1/harry-potter-01.jpg",
        price: 50,
    }, {
        name: "English Dictionary",
        brand: "Collins",
        description: "English Dictionary 2021 Edition",
        category: "Books & Stationeries",
        image: "https://i.ibb.co/C8RprDp/dicitionery-01.jpg",
        price: 30,
    }, {
        name: "Colour Pencils",
        brand: "Faber-Castell",
        description: "Full set 50 colours",
        category: "Books & Stationeries",
        image: "https://i.ibb.co/t3CDhcy/colour-pencil-01.jpg",
        price: 200,
    },]

module.exports = productsSeed;
